---
- name: add release key
  apt_key:
    url: https://download.ceph.com/keys/release.asc
    state: present
- name: add Ceph packages to repository
  apt_repository:
    repo: deb https://download.ceph.com/debian-luminous {{ ansible_lsb.codename|lower }} main
#    state: present
#    filename: '/etc/apt/sources.list.d/ceph.list'
- name: Update repositories cache and install "ceph-deploy" package
  apt:
    name: ceph-deploy
    update_cache: yes
