---
- name: create cluster folder
  file:
    path: ~/cluster
    state: directory
    mode: 0755
- name: install ceph on all nodes
  shell: ceph-deploy install "{{ item }}"
  with_items:
    - "adm"
    - "node-1"
    - "node-2"
    - "node-3"
  args:
    chdir: ~/cluster
- name: create new cluster
  shell: ceph-deploy new node-1 node-2 node-3
  args:
    chdir: ~/cluster
- name: deploy the monitor node
  shell: ceph-deploy --overwrite-conf mon create-initial
  args:
    chdir: ~/cluster
- name: copy configuration file and admin key
  shell: ceph-deploy --overwrite-conf admin "{{ item }}"
  with_items:
    - "node-1"
    - "node-2"
    - "node-3"
  args:
    chdir: ~/cluster
- name: add OSDs
#  shell: "ceph-deploy osd create {{ item }}:/dev/vdb"
  shell: "ceph-deploy osd create --data /dev/vdb {{ item }}"
  with_items:
    - "node-1"
    - "node-2"
    - "node-3"
  args:
    chdir: ~/cluster
